name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Git checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: '10'

    - name: Install dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: hyperfine
        version: 1.0

    - name: Run tests
      run: make test

    - name: Run benchmark
      run: make benchmark
